run:
  issues-exit-code: 1
  skip-dirs:
    - hack
    - vendor

  skip-files:
    - zz_generated.*.go

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - misspell
    - nakedret
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

linters-settings:
  govet:
    check-shadowing: true
  goimports:
    local-prefixes: k8c.io/operating-system-manager
