# Copyright 2021 The Operating System Manager contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

presubmits:
  #########################################################
  # verify, build, and unit tests
  #########################################################
  - name: pull-operating-system-manager-verify-boilerplate
    always_run: true
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/operating-system-manager.git"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: quay.io/kubermatic-labs/boilerplate:v0.1.1
          command:
            - make
          args:
            - verify-boilerplate

  - name: pull-operating-system-manager-verify-codegen
    always_run: true
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/operating-system-manager.git"
    path_alias: k8c.io/operating-system-manager
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: golang:1.17.5
          command:
            - make
          args:
            - verify-codegen
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 1Gi
              cpu: 1

  - name: pull-operating-system-manager-verify-crds-openapi
    always_run: true
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/operating-system-manager.git"
    path_alias: k8c.io/operating-system-manager
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: golang:1.17.5
          command:
            - make
          args:
            - verify-crds-openapi
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 1Gi
              cpu: 1

  - name: pull-operating-system-manager-license-validation
    always_run: true
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/operating-system-manager.git"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/wwhrd:0.2.1-1
          command:
            - make
          args:
            - verify-licence
          resources:
            requests:
              memory: 1Gi
              cpu: 1
            limits:
              memory: 2Gi
              cpu: 2

  - name: pull-operating-system-manager-lint
    always_run: true
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/operating-system-manager.git"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: golangci/golangci-lint:v1.42.1
          command:
            - make
          args:
            - lint
          resources:
            requests:
              memory: 1Gi
              cpu: 800m
            limits:
              memory: 2Gi

  - name: pull-operating-system-manager-test
    always_run: true
    decorate: true
    error_on_eviction: true
    clone_uri: "ssh://git@github.com/kubermatic/operating-system-manager.git"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: golang:1.17.5
          command:
            - make
          args:
            - test
          resources:
            requests:
              memory: 1Gi
              cpu: 500m

postsubmits:
  - name: post-operating-system-manager-image
    always_run: true
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/operating-system-manager.git"
    branches:
      - ^master$
      # Match on tags
      - ^v\d+\.\d+\.\d+.*
    labels:
      preset-docker-push: "true"
      preset-goproxy: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.17-node-16-kind-0.11-4
          command:
            - /bin/bash
            - -c
            - |
              set -euo pipefail &&
              start-docker.sh
              docker login -u $QUAY_IO_USERNAME -p $QUAY_IO_PASSWORD quay.io &&
              make download-gocache docker-image-publish
          # docker-in-docker needs privileged mode
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 100m
              memory: 1Gi

  - name: post-operating-system-manager-upload-gocache
    always_run: true
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/operating-system-manager.git"
    branches:
      - ^master$
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.17-node-16-kind-0.11-4
          command:
            - "./hack/ci/upload-gocache.sh"
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
