/*
Copyright 2021 The Operating System Manager contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "k8c.io/operating-system-manager/pkg/crd/osm/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeOperatingSystemProfiles implements OperatingSystemProfileInterface
type FakeOperatingSystemProfiles struct {
	Fake *FakeOperatingsystemmanagerV1alpha1
	ns   string
}

var operatingsystemprofilesResource = schema.GroupVersionResource{Group: "operatingsystemmanager.k8c.io", Version: "v1alpha1", Resource: "operatingsystemprofiles"}

var operatingsystemprofilesKind = schema.GroupVersionKind{Group: "operatingsystemmanager.k8c.io", Version: "v1alpha1", Kind: "OperatingSystemProfile"}

// Get takes name of the operatingSystemProfile, and returns the corresponding operatingSystemProfile object, and an error if there is any.
func (c *FakeOperatingSystemProfiles) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.OperatingSystemProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(operatingsystemprofilesResource, c.ns, name), &v1alpha1.OperatingSystemProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OperatingSystemProfile), err
}

// List takes label and field selectors, and returns the list of OperatingSystemProfiles that match those selectors.
func (c *FakeOperatingSystemProfiles) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.OperatingSystemProfileList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(operatingsystemprofilesResource, operatingsystemprofilesKind, c.ns, opts), &v1alpha1.OperatingSystemProfileList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.OperatingSystemProfileList{ListMeta: obj.(*v1alpha1.OperatingSystemProfileList).ListMeta}
	for _, item := range obj.(*v1alpha1.OperatingSystemProfileList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested operatingSystemProfiles.
func (c *FakeOperatingSystemProfiles) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(operatingsystemprofilesResource, c.ns, opts))

}

// Create takes the representation of a operatingSystemProfile and creates it.  Returns the server's representation of the operatingSystemProfile, and an error, if there is any.
func (c *FakeOperatingSystemProfiles) Create(ctx context.Context, operatingSystemProfile *v1alpha1.OperatingSystemProfile, opts v1.CreateOptions) (result *v1alpha1.OperatingSystemProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(operatingsystemprofilesResource, c.ns, operatingSystemProfile), &v1alpha1.OperatingSystemProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OperatingSystemProfile), err
}

// Update takes the representation of a operatingSystemProfile and updates it. Returns the server's representation of the operatingSystemProfile, and an error, if there is any.
func (c *FakeOperatingSystemProfiles) Update(ctx context.Context, operatingSystemProfile *v1alpha1.OperatingSystemProfile, opts v1.UpdateOptions) (result *v1alpha1.OperatingSystemProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(operatingsystemprofilesResource, c.ns, operatingSystemProfile), &v1alpha1.OperatingSystemProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OperatingSystemProfile), err
}

// Delete takes name of the operatingSystemProfile and deletes it. Returns an error if one occurs.
func (c *FakeOperatingSystemProfiles) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(operatingsystemprofilesResource, c.ns, name), &v1alpha1.OperatingSystemProfile{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOperatingSystemProfiles) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(operatingsystemprofilesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.OperatingSystemProfileList{})
	return err
}

// Patch applies the patch and returns the patched operatingSystemProfile.
func (c *FakeOperatingSystemProfiles) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.OperatingSystemProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(operatingsystemprofilesResource, c.ns, name, pt, data, subresources...), &v1alpha1.OperatingSystemProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OperatingSystemProfile), err
}
