# Copyright 2021 The Operating System Manager contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: operatingsystemmanager.k8c.io/v1alpha1
kind: OperatingSystemProfile
metadata:
  name: test-osp
  namespace: kube-system
spec:
  osName: "ubuntu"
  osVersion: "20.04"
  supportedCloudProviders:
    - name: "aws"
      spec:
        region: "us-west-1a"
  units:
    - name: test-unit-1
      enable: true
      content: "test unit content"
  files:
    - path: "/tmp/testfile-1"
      permissions: 0644
      content:
        inline:
          data: "test data"
          encoding: "none"
    - path: "/tmp/testfile-2"
      permissions: 0644
      content:
        inline:
          encoding: b64
          data: |-
            mkdir -p /opt/bin/
            mkdir -p /var/lib/calico
            mkdir -p /etc/kubernetes/manifests
            mkdir -p /etc/cni/net.d
            mkdir -p /opt/cni/bin
            if [ ! -f /opt/cni/bin/loopback ]; then
                curl -L https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-amd64-v0.8.7.tgz | tar -xvzC /opt/cni/bin -f -
            fi
            {{- /* kubelet */}}
            if [ ! -f /opt/bin/kubelet ]; then
                curl -Lfo /opt/bin/kubelet https://storage.googleapis.com/kubernetes-release/release/v{{ .KubeletVersion }}/bin/linux/amd64/kubelet
                chmod +x /opt/bin/kubelet
            fi
            if [[ ! -x /opt/bin/health-monitor.sh ]]; then
                curl -Lfo /opt/bin/health-monitor.sh https://raw.githubusercontent.com/kubermatic/machine-controller/8b5b66e4910a6228dfaecccaa0a3b05ec4902f8e/pkg/userdata/scripts/health-monitor.sh
                chmod +x /opt/bin/health-monitor.sh
            fi

            
              
